/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.passencoderdecoderwebservice;

public class PassEncoderDecoder {
    public boolean someLibraryMethod() {
        return true;
    }
}
